#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CalcAndroidBtns.Resource", IsApplication=true)]

namespace CalcAndroidBtns
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040012
			public const int btn0 = 2130968594;
			
			// aapt resource value: 0x7f040003
			public const int btn1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int btn2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int btn3 = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int btn4 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int btn5 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int btn6 = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int btn7 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int btn8 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int btn9 = 2130968591;
			
			// aapt resource value: 0x7f040006
			public const int btnAdd = 2130968582;
			
			// aapt resource value: 0x7f040014
			public const int btnDiv = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int btnEql = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int btnMul = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int btnSub = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int resultText = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int resultText2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int wrapper1 = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int wrapper2 = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int wrapper3 = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int wrapper4 = 2130968593;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
